apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tororu-operator.fullname" . }}
  labels:
    {{- include "tororu-operator.labels" . | nindent 4 }}
data:
  tororu-operator.yaml: |
    emtpy: dummy