# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tororu-operator.fullname" . }}
  labels:
    {{- include "tororu-operator.labels" . | nindent 4 }}
type: Opaque
data:
  ADM_CONTROLLER_CERT: {{ .Values.config.admControllerHttpsCert }}
  ADM_CONTROLLER_KEY: {{ .Values.config.admControllerHttpsKey }}
