//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TororuResource) DeepCopyInto(out *TororuResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Consumers.DeepCopyInto(&out.Consumers)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TororuResource.
func (in *TororuResource) DeepCopy() *TororuResource {
	if in == nil {
		return nil
	}
	out := new(TororuResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TororuResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TororuResourceConsumers) DeepCopyInto(out *TororuResourceConsumers) {
	*out = *in
	if in.RO != nil {
		in, out := &in.RO, &out.RO
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TororuResourceConsumers.
func (in *TororuResourceConsumers) DeepCopy() *TororuResourceConsumers {
	if in == nil {
		return nil
	}
	out := new(TororuResourceConsumers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TororuResourceList) DeepCopyInto(out *TororuResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TororuResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TororuResourceList.
func (in *TororuResourceList) DeepCopy() *TororuResourceList {
	if in == nil {
		return nil
	}
	out := new(TororuResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TororuResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
